spring:
  application:
    name: phf-back-end
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.yekpjpfhkjaydufdzxgo.supabase.co:5432/postgres?sslmode=require&ApplicationName=phf-back-end&preferQueryMode=simple}
    username: ${SPRING_DATASOURCE_USERNAME:pharama}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 120000
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: -1
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
      register-mbeans: true
      connection-init-sql: SELECT 1
      allow-pool-suspension: true

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: phf
        jdbc.time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    schemas: phf
    defaultSchema: phf
    baseline-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true
    validate-on-migrate: false
    connect-retries: 50
    connect-retries-interval: 3
    init-sql: SELECT 1
    fail-on-missing-locations: false

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: OFF
