spring:
  application:
    name: phf-back-end

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://db.yekpjpfhkjaydufdzxgo.supabase.co:5432/postgres?sslmode=require&ApplicationName=phf-back-end
    username: pharama         # hoặc tài khoản bạn tạo trong Supabase
    password: 123    # thay bằng mật khẩu thật
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 15000
      idle-timeout: 60000
      max-lifetime: 300000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: phf
        jdbc.time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  flyway:
    enabled: true
    schemas: phf
    defaultSchema: phf
    baseline-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true
    validate-on-migrate: false

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: OFF
